-- CONSULTA 1
-- CONSULTE O RANKING DOS 10 MAIORES COLABOLADORES COM BASE NO TOTAL EM REAIS DE VENDAS DO ANO 2016
--OBS: VIEW 1
SELECT TOP 10 * FROM ranking_vendas
-- CONSULTA 2
-- CONSULTE OS EMPREENDIMENTOS COM MAIOR VALOR DE VENDA EM ORDER DESC
SELECT TOP 100 E.CODEMPREENDIMENTO AS COD_EMPREENDIMENTOFROM, U.VALOR AS VALOR_IMOVEL
FROM EMPREENDIMENTO E, UNIDADE U
WHERE E.CODUNIDADE = U.CODUNIDADE
AND	  E.CODEMPREENDIMENTO = U.CODEMPREENDIMENTO
ORDER BY U.VALOR DESC

-- CONSULTA 3
-- CONSULTE TODOS OS CLIENTES QUE ESTAO COM PAGAMENTOS PENDENTES
-- OBS: VIEW 2
SELECT * FROM lista_clientes_pg_pendende
-- CONSULTA 4
-- CONSULTE O HISTORICO DE COMPRA REFERENTE AO ULTIMO ANO DE EXERCICIO
SELECT U.*, C.MATRICULA AS MATRICULA_COLABORADOR, V.DATAVENDA AS DATA_VENDA, V.VALORVENDA AS VALOR, V.STATUS AS CONDICAO
FROM VENDAS V, COLABOLADOR C, UNIDADE U
WHERE V.CODCOLABOLADOR = C.CODCOLABOLADOR
AND   V.CODUNIDADE = U.CODUNIDADE
AND DATAVENDA > '20160101'
-- CONSULTA 5
-- CONSULTE O EMPRRENDIMENTO COM MAIOR VALOR DE VENDA. OU SEJA, O QUE DARÁ MAIS LUCRO PRO COLABORADOR. E MOSTRE OS DADOS DO EMPREENDIMENTO
SELECT TOP 1 E.*, U.PRECOBASE, * 
FROM UNIDADE U, EMPREENDIMENTO E
WHERE U.CODEMPREENDIMENTO = E.CODEMPREENDIMENTO
AND	  U.CODUNIDADE = E.CODUNIDADE
ORDER BY U.VALOR DESC 
-- CONSULTA 6
-- CONSULTE A QUANTIDADE DE EMPREENDIMENTO VENDIDOS NO ULTIMO ANO E O TOTAL ARRECADADO
SELECT COUNT(CODVENDA) AS QUANTIDADE_VENDAS_2016, SUM(VALORVENDA)
FROM VENDAS
WHERE DATAVENDA > '20160101'
-- CONSULTA 7
-- CONSULTE A MÉDIA ($$) RECEBIDA POR CADA COLABORADOR E MOSTRE-OS POR ORDEM DE DECRESCENTE POR VALOR
SELECT C.MATRICULA AS MATRICULA_COLAB, AVG(V.VALORVENDA) AS MEDIA_$, 
FROM COLABOLADOR C, VENDAS V
WHERE C.CODCOLABOLADOR = V.CODCOLABOLADOR
ORDER BY V.VALORVENDA DESC
-- CONSULTA 8
-- CONSULTE OS COLABORADORES QUE RESERVARAM UMA COMPRA DE APARTAMENTO PARA ALGUM CLIENTE
SELECT C.* 
FROM COLABOLADOR C, PESSOA P, RESERVA R
WHERE C.CODPESSOA = P.CODPESSOA
AND   R.CODCOLABOLADOR = C.CODCOLABOLADOR

-- CONSULTA 9
-- CONSULTE A QUANTIDADE DE COLABOLADOR POR EQUIPE, MOSTRE A EQUIPE E A QNTD
SELECT E.CODEQUIPE AS EQUIPE, COUNT(C.CODCOLABOLADOR)
FROM EQUIPE E, COLABOLADOR C
WHERE E.CODCOLABOLADOR = C.CODCOLABOLADOR

-- CONSULTA 10 * MELHORAR ESSA
-- CONSULTE OS DADOS DO COLABOLADOR RELATIVOS A CARGO, EQUIPE E LOJAS QUE ESTA ALOCADO COM SALARIO MAIOR QUE 2000 MIL
SELECT C.MATRICULA AS MATRICULA, E.CODEQUIPE AS EQUIPE, C.NOME AS CARGO, L.NOME AS NOME_LOJA, L.TIPOSERVICO AS SERVICO
FROM COLABOLADOR C, LOJAS L, EQUIPES E, CARGOS C
WHERE C.CODCOLABOLADOR = L.CODCOLABOLADOR
AND C.CODCOLABOLADOR = E.CODCOLABOLADOR
AND C.CODCOLABOLADOR = C.CODCOLABOLADOR
AND C.SALARIO > 2000
ORDER BY C.SALARIO DESC