-- ranking top 10 vendas de 2016
CREATE VIEW ranking_vendas AS 
SELECT TOP 10 V.VALOR AS VALOR_TOTAL_VENDAS, C.MATRICULA AS MATRICULA, P.NOME AS COLABOLADOR
FROM VENDAS V, COLABORADOR C, PESSOA P 
WHERE V.CODCOLABORADOR = C.CODCOLABORADOR AND
      C.CODPESSOA = P.CODPESSOA AND
	  V.DATAVENDA >= '20160101'
	  
SELECT * FROM ranking_vendas

-- lista de clientes pendentes
CREATE VIEW lista_clientes_pg_pendende AS
SELECT P.NOME AS CLIENTE, PG.VALOR AS SALDO_DEVEDOR, PG.DATA
FROM PESSOA P, PAGAMENTOS PG, CLIENTE C
WHERE P.CODPESSOA = C.CODPESSOA AND
	  PG.CODCLIENTE = C.CODCLIENTE AND
	  PG.STATUS IS NOT LIKE '%QUITADO%' 
	  
SELECT * FROM lista_clientes_pg_pendende